import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import StoreProvider from "./store/StoreProvider";
import FloatingThemeToggle from "./components/FloatingThemeToggle";

export const metadata: Metadata = {
  title: "Jacob's Space",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <StoreProvider>
          <Navbar />
          <main className="pt-24 pb-24">{children}</main>
          <FloatingThemeToggle />
        </StoreProvider>
      </body>
    </html>
  );
}
